"""empty message

Revision ID: 93cb9d0a49b3
Revises: d5f0b7f99a44
Create Date: 2023-03-30 20:09:31.173626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93cb9d0a49b3'
down_revision = 'd5f0b7f99a44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
