"""empty message

Revision ID: f7f4e9e6e6d4
Revises: 204f225600aa
Create Date: 2023-03-24 10:44:02.858481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f4e9e6e6d4'
down_revision = '204f225600aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduling_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('message', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=False))
        batch_op.create_foreign_key("fk_notifications_scheduling_id", 'schedulings', ['scheduling_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint("fk_notifications_scheduling_id", type_='foreignkey')
        batch_op.drop_column('read')
        batch_op.drop_column('message')
        batch_op.drop_column('type')
        batch_op.drop_column('scheduling_id')

    # ### end Alembic commands ###
